-- SQL Schema for Sunniside Cornerstone Church Database (Supabase)

-- 1. Create Events Table
CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    event_date timestamptz NOT NULL,
    description text,
    location text,
    image_data text,
    recurring_type text,
    recurring_details text
);

-- 2. Create Prayer Requests Table
CREATE TABLE IF NOT EXISTS prayer_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    phone text,
    address text,
    request_text text NOT NULL,
    is_archived boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- 3. Create Gallery Images Table
CREATE TABLE IF NOT EXISTS gallery_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_name text NOT NULL,
    image_data text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE prayer_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;

-- 5. Drop existing policies to prevent conflicts
DROP POLICY IF EXISTS "Allow public read access" ON events;
DROP POLICY IF EXISTS "Allow public insert" ON events;
DROP POLICY IF EXISTS "Allow public update" ON events;
DROP POLICY IF EXISTS "Allow public delete" ON events;
DROP POLICY IF EXISTS "Allow authenticated insert" ON events;
DROP POLICY IF EXISTS "Allow authenticated update" ON events;
DROP POLICY IF EXISTS "Allow authenticated delete" ON events;

DROP POLICY IF EXISTS "Allow public read access" ON prayer_requests;
DROP POLICY IF EXISTS "Allow public insert" ON prayer_requests;
DROP POLICY IF EXISTS "Allow public update" ON prayer_requests;
DROP POLICY IF EXISTS "Allow public delete" ON prayer_requests;
DROP POLICY IF EXISTS "Allow authenticated read" ON prayer_requests;
DROP POLICY IF EXISTS "Allow authenticated update" ON prayer_requests;
DROP POLICY IF EXISTS "Allow authenticated delete" ON prayer_requests;

DROP POLICY IF EXISTS "Allow public read access" ON gallery_images;
DROP POLICY IF EXISTS "Allow public insert" ON gallery_images;
DROP POLICY IF EXISTS "Allow public delete" ON gallery_images;
DROP POLICY IF EXISTS "Allow authenticated insert" ON gallery_images;
DROP POLICY IF EXISTS "Allow authenticated delete" ON gallery_images;

-- 6. Create policies for events table (Read for public, Write for authenticated)
CREATE POLICY "Allow public read access" ON events FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON events FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update" ON events FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete" ON events FOR DELETE TO authenticated USING (true);

-- 7. Create policies for prayer_requests table (Insert for public, CRUD for authenticated)
CREATE POLICY "Allow public insert" ON prayer_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated read" ON prayer_requests FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated update" ON prayer_requests FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete" ON prayer_requests FOR DELETE TO authenticated USING (true);

-- 8. Create policies for gallery_images table (Read for public, Write for authenticated)
CREATE POLICY "Allow public read access" ON gallery_images FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON gallery_images FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated delete" ON gallery_images FOR DELETE TO authenticated USING (true);